//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uuregistration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uuregistration.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factuur Jaar.
        /// </summary>
        public static string FactuurJaar {
            get {
                return ResourceManager.GetString("FactuurJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het doel van dit project is het in practijk brengen van de theoretische lessen. Voldende technieken in de project worden toegepast:.
        /// </summary>
        public static string InleidingText {
            get {
                return ResourceManager.GetString("InleidingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inleiding.
        /// </summary>
        public static string InleidingTitel {
            get {
                return ResourceManager.GetString("InleidingTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies taal.
        /// </summary>
        public static string LanguageChoose {
            get {
                return ResourceManager.GetString("LanguageChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er wordt wervacht een basis &quot;Uur registratie en facturatie&quot; systeem te maken dat het toelaat uur registraties te beheren en te factureren..
        /// </summary>
        public static string OmschrijvingText {
            get {
                return ResourceManager.GetString("OmschrijvingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string OmschrijvingTitel {
            get {
                return ResourceManager.GetString("OmschrijvingTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uur registratie en facturatie systeem.
        /// </summary>
        public static string ProjectNaam {
            get {
                return ResourceManager.GetString("ProjectNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het is een project 3de jaar informatica Groep T Graduaten.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Uur registratie en facturatie systeem.
        /// </summary>
        public static string WelcomeTitel {
            get {
                return ResourceManager.GetString("WelcomeTitel", resourceCulture);
            }
        }
    }
}
